# Generated by Django 2.1.7 on 2019-04-02 11:48

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(blank=True, help_text="A comma-separated list of tags", through="taggit.TaggedItem", to="taggit.Tag", verbose_name="Tags"),
        ),
    ]
