# Generated by Django 2.1.7 on 2019-04-01 16:19

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='default.png', upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
